name: flutter_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  get: ^4.7.2
  flutter_svg: ^2.1.0
  http: ^1.4.0
  #  datetimeformat
  intl: ^0.20.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  mime_type: ^1.0.1
  http_parser: ^4.1.2
  equatable: ^2.0.7
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  get_it: ^8.0.3
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  lottie: ^3.3.1
  go_router: ^15.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


